FROM node:20-alpine

ENV NPM_CONFIG_IGNORE_SCRIPTS=true

WORKDIR /app

COPY package.json yarn.lock* ./
RUN npm install --legacy-peer-deps --only=dev

COPY . .

WORKDIR /app/apps/web

RUN npm install --legacy-peer-deps
RUN npm run build

EXPOSE 3000

CMD ["npm","start"]

CMD ["npm","start"]