FROM node:20-alpine

ENV NPM_CONFIG_IGNORE_SCRIPTS=true

WORKDIR /app

COPY . .

WORKDIR /app/apps/server

RUN npm install --legacy-peer-deps
RUN npm run db:generate
RUN npm run build

EXPOSE 8000

CMD ["sh", "-c", "npm run db:push && npm run start"]